common:
  lables:
    common: "labels"
  namespace: teleskope
  
backend:
  enabled: true
  image: idobry/teleskope_backend:sha-ec71349
  command: ["./teleskope_backend", "run"]
  replicas: 1
  env:
  - name: PORT
    value: "3000"
  service:
    port: 3000
    targetPort: 3000
  ingress:
    enabled: true
    hosts:
    - host: teleskope.io
      paths: ["/ns", "/dep", "/list", "/ws"]
frontend:
  enabled: true
  image: efrat19/teleskope-frontend:amd64-22f456a1de2636b182e11e16781ee0f84cdddfa1
  env:
  - name: VUE_APP_WS_ENDPOINT
    value: "ws://teleskope.io/ws"
  service:
    port: 80
    targetPort: 80
  ingress:
    enabled: true
    hosts:
    - host: teleskope.io
      paths: ["/"]
