{{- if .Values.backend.enabled -}}
{{- if .Values.backend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "master.name" . }}-backend-sa
  {{- if .Values.backend.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.backend.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "master.name" . }}-backend
{{ include "master.labels" . | indent 4 }}
{{ toYaml .Values.common.lables | indent 4 }}
{{- end }}
{{- end }}
