{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "master.fullname" . }}-frontend-svc
  labels:
{{ include "master.labels" . | indent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "master.fullname" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
