{{- if .Values.frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "master.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "master.name" . }}-frontend
{{ include "master.labels" . | indent 4 }}
{{ toYaml .Values.common.lables | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "master.fullname" . }}-frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- with .Values.frontend.replicas }}
  replicas: {{ . }}
{{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "master.fullname" . }}-frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
{{ toYaml .Values.common.lables | indent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.frontend.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
          # {{ if .Values.frontend.ingress.enabled }}
          # - name: YAD2_HOSTNAME
          #   value: {{ (index .Values.frontend.ingress.hosts 0).host | quote }}
          # {{- end }}
          {{- toYaml .Values.frontend.env | nindent 10 }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
          {{- if .Values.frontend.enableResources }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.command }}
          command: {{ .Values.frontend.command }}
          {{- end }}
          {{- if .Values.frontend.probes.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.livenessPath | default .Values.frontend.probes.path }}
              port: http
            timeoutSeconds: {{ .Values.frontend.probes.timeout }}
            # initialDelaySeconds: 10
            # failureThreshold: 1
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.readinessPath | default .Values.frontend.probes.path }}
              port: http
            # initialDelaySeconds: 10
            # successThreshold: 3
            # failureThreshold: 1
            timeoutSeconds: {{ .Values.frontend.probes.timeout }}
          {{- end }}
      {{- with .Values.frontend.nodeSelector }}
{{- if .Values.frontend.extraContainers }}
{{ toYaml .Values.frontend.extraContainers | indent 8}}
{{- end }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
