apiVersion: v1
kind: ServiceAccount
metadata:
  name: teleskope
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: teleskope
  name: teleskope
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  - batch
  resources:
  - pods
  - jobs
  - namespaces
  - services
  - deployments
  - replicationcontrollers
  - replicasets
  - daemonsets
  verbs:
  - get
  - list
  - watch
  ---
  kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: teleskope-binding
subjects:
- kind: ServiceAccount
  name: teleskope
roleRef:
  kind: ClusterRole
  name: teleskope
  apiGroup: rbac.authorization.k8s.io
