apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: teleskope
    app.kubernetes.io/name: teleskope-backend
  name: teleskope
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  - batch
  resources:
  - pods
  - jobs
  - namespaces
  - services
  - deployments
  - replicationcontrollers
  - replicasets
  - daemonsets
  verbs:
  - get
  - list
  - watch
